export const CHOOSE_BASKET = 'CHOOSE_BASKET';
export const SELECT_TASKS = 'SELECT_TASKS';
export const DELEGATED_TASKS_DETAILS = 'DELEGATED_TASKS_DETAILS';
export const CHOOSE_AVATAR = 'CHOOSE_AVATAR';